# Generated by Django 4.2.5 on 2023-09-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_game_home_team_player_assists_player_blocks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shot",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
