# Generated by Django 4.2.5 on 2023-09-09 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_shot_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="game",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.game",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="is_home",
            field=models.BooleanField(default=False),
        ),
    ]
