# Generated by Django 4.2.5 on 2023-09-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_team_game_team_is_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
